"""first table

Revision ID: 98b3fe70a7fb
Revises: 
Create Date: 2024-01-20 17:48:53.501859

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98b3fe70a7fb'
down_revision = None
branch_labels = None
depends_on = None

type_enum = sa.Enum("pagar", "receber", name="type_enum")

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Conta',
    sa.Column('ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=30), nullable=True),
    sa.Column('value', sa.Numeric(), nullable=True),
    sa.PrimaryKeyConstraint('ID')
    )

    op.add_column('Conta', sa.Column('type', type_enum, nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Conta')
    # ### end Alembic commands ###
