"""fornecedor_cliente

Revision ID: ea6367bb4b74
Revises: 98b3fe70a7fb
Create Date: 2024-01-23 11:46:45.802103

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea6367bb4b74'
down_revision = '98b3fe70a7fb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Conta',
    sa.Column('ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=30), nullable=True),
    sa.Column('value', sa.Numeric(), nullable=True),
    sa.Column('type', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_table('fornecedor_cliente',
    sa.Column('ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('ID')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fornecedor_cliente')
    op.drop_table('Conta')
    # ### end Alembic commands ###
